### PR TITLE
Fix handling jars without manifest

### PR DESCRIPTION
**Pull request by iherasymenko**
An example of such a jar: https://repo1.maven.org/maven2/javax/inject/javax.inject/1/javax.inject-1.jar

P.S. I know that there's a properly modularized Jakarta EE replacement, but I believe the plugin should still support the subject and do not throw an NPE if it encounters a jar like that.

### CODE REVIEW

**Review by jjohannes — CHANGES_REQUESTED** [review]
@iherasymenko Thanks for this fix! Could you please not bump the Gradle version. I want to stay on 6.4 to make sure the plugin works with 6.4 as minimal version.

And would you mind adding a test that reproduces the NPE with "javax.inject-1.jar"? You can add a test with a minimal build doing that to `ExtraJavaModuleInfoTest`.

**Comment by iherasymenko** [comment]
@jjohannes thanks for the review. I applied the changes that you requested.

Btw, in order to make sure the plugin is compatible with 6.4, we could amend the test runner declaration with the "withVersion" option. I.e. make it looks as follows. 
```
    GradleRunner gradleRunnerFor(List<String> args) {
        GradleRunner.create()
                .withVersion("6.4")
                .forwardOutput()
                .withPluginClasspath()
                .withProjectDir(testFolder.root)
                .withArguments(args)
    }
```

I can create a separate PR with the version bump and this change.

**Review by jjohannes — APPROVED** [review]
Thanks for adding the tests @iherasymenko. This looks good now.

Thanks for offering to do another PR to bump the Gradle version, but I would like to keep the it as it is to compile against the right `gradleApi()` as long as there is not very good reason to move to a newer version.

I'll merge this and do a new release of the plugin soon.

**Comment by msgilligan** [comment]
I just stumbled upon this issue (also with `javax.inject`) trying to migrate a module from Java Modularity Plugin to to this plugin. Will you be releasing 0.2 soon?

**Comment by iherasymenko** [comment]
@msgilligan there is a properly modularized version of `java.inject`: `jakarta.inject:jakarta.inject-api:1.0.1`

I solved the issue as follows by substituting one with the other.

```
configurations.all { Configuration configuration ->
    configuration.resolutionStrategy.dependencySubstitution {
        substitute module('javax.inject:javax.inject') because 'it is not properly modularized' with module('jakarta.inject:jakarta.inject-api:1.0.1')
    }
}
```

**Comment by jjohannes** [comment]
@iherasymenko @msgilligan I just published 0.2 which includes this fix. Let me know if you encounter any issues.

**Comment by msgilligan** [comment]
@iherasymenko Thanks! I didn't know you could do that. That may come in handy in the future.

@jjohannes 0.2 seems to be working for me. Thanks!

**Pull request merged**
